// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_let_the_battles_begin = "CgkI_J-eqbEYEAIQAg"; // <GPGSID>
        public const string achievement_testincremental = "CgkI_J-eqbEYEAIQCA"; // <GPGSID>
        public const string achievement_hitting_it_off = "CgkI_J-eqbEYEAIQAw"; // <GPGSID>
        public const string achievement_magical_mayhem = "CgkI_J-eqbEYEAIQBA"; // <GPGSID>
        public const string leaderboard_leaders = "CgkI_J-eqbEYEAIQBQ"; // <GPGSID>
        public const string achievement_the_start_of_an_adventure = "CgkI_J-eqbEYEAIQAQ"; // <GPGSID>
        public const string achievement_is_the_best_offence = "CgkI_J-eqbEYEAIQBg"; // <GPGSID>
        public const string achievement_testachievements = "CgkI_J-eqbEYEAIQBw"; // <GPGSID>

}

